---
- name: Update web servers
  hosts: devserver
  remote_user: root
  vars:
    image_repo: 780202038201.dkr.ecr.eu-north-1.amazonaws.com/custody-keys-bridge
    timestamp_tag: "{{ lookup('pipe', 'date +%Y%m%d%H%M') }}"
    full_image: "{{ image_repo }}:{{ timestamp_tag }}"
  tasks:
  - name: commands to deploy keys-bridge
    ansible.builtin.shell: |
      cd /root/prod/custody-keys-bridge
      git pull
      cd /root/prod/custody-keys-bridge/rox-custody_common-modules
      git pull
      cd ..
      aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 780202038201.dkr.ecr.eu-north-1.amazonaws.com
      docker build -t {{ full_image }} .
      docker push {{ full_image }}
      kubectl set image deployment/custody-keys-bridge custody-keys-bridge={{ full_image }} --record
    register: keys_bridge_output

  - name: delete the image from the server  
    ansible.builtin.shell: |
      docker images --format '{{ "{{.Repository}}:{{.Tag}}" }}' | grep '^{{ image_repo }}:' | xargs -r docker rmi
    when: keys_bridge_output is success


  - name: show output
    debug:
      var: keys_bridge_output.stdout_lines







