apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: solution-api-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "solution-api-secrets"
        objectType: secretsmanager