apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: super-admin-api-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "super-admin-api-secrets"
        objectType: secretsmanager